foldersTree = gFld("<i>JRun Console Root</i>", "/mock/root.jsp")
	aux1 = insFld(foldersTree, gFld("machine1", "/mock/machine1.jsp"))
	
	      aux2 = insFld(aux1, gFld("jsm-default", "/mock/jsm-default.jsp"))

		      aux3 = insFld(aux2, gFld("services", "/mock/services.jsp"))
					aux4 = insFld(aux3, gFld("jse", "/mock/jse.jsp"))
						insDoc(aux4, gLnk(2, "General", "/mock/jse_general.jsp"))
					  	insDoc(aux4, gLnk(2, "Mappings", "/mock/jse_mappings.jsp"))
					  	insDoc(aux4, gLnk(2, "Aliases", "/mock/jse_aliases.jsp"))
					  	insDoc(aux4, gLnk(2, "MIME Filters", "/mock/jse_mimeFilters.jsp"))
					  	insDoc(aux4, gLnk(2, "Multi-Home", "/mock/jse_multiHome.jsp"))
					  	insDoc(aux4, gLnk(2, "Session Tracking", "/mock/jse_sessionTracking.jsp"))
					  	insDoc(aux4, gLnk(2, "JSP Page Compilation", "/mock/jse_pageCompilation.jsp"))
  					  	insDoc(aux4, gLnk(2, "Code Taglets", "/mock/jse_codeTaglets.jsp"))
					  	insDoc(aux4, gLnk(2, "File Settings", "/mock/jse_fileSettings.jsp"))
						aux5 = insFld(aux4, gFld("&lt;CF_Anywhere&gt;", "/mock/CFA.jsp"))
		  					  	insDoc(aux5, gLnk(2, "CF Tags", "/mock/CFA_tags.jsp"))
		  					  	insDoc(aux5, gLnk(2, "Web Application", "/mock/CFA_webApp"))
		  					  	insDoc(aux5, gLnk(2, "Data Sources", "/mock/CFA_dsn.jsp"))
		  					  	insDoc(aux5, gLnk(2, "CFForm Applets", "/mock/CFA_formApplets.jsp"))
								
			      aux4 = insFld(aux3, gFld("jcp", "/mock/jcp.jsp"))
			      aux4 = insFld(aux3, gFld("jseweb", "/mock/jseweb.jsp"))
			      aux4 = insFld(aux3, gFld("jws", "/mock/jws.jsp"))
						insDoc(aux4, gLnk(2, "General", "/mock/jws_general.jsp"))
					  	insDoc(aux4, gLnk(2, "Endpoints", "/mock/jws_endpoints.jsp"))
					  	insDoc(aux4, gLnk(2, "Service", "/mock/jws_service.jsp"))
					  	insDoc(aux4, gLnk(2, "Paths", "/mock/jws_paths.jsp"))
			      aux4 = insFld(aux3, gFld("zeus", "/mock/zeus.jsp"))
	  			insDoc(aux2, gLnk(2, "General JSM Settings", "/mock/general.jsp"))
	  			insDoc(aux2, gLnk(2, "License", "/mock/license.jsp"))
				
	      aux2 = insFld(aux1, gFld("jsm-dre", "/mock/jsm-dre.jsp"))
		      aux3 = insFld(aux2, gFld("services", "/mock/services.jsp"))
	  			insDoc(aux2, gLnk(2, "General JSM Settings", "/mock/general.jsp"))
	  			insDoc(aux2, gLnk(2, "License", "/mock/license.jsp"))
			  
	      aux2 = insFld(aux1, gFld("security", "/mock/security.jsp"))
				insDoc(aux2, gLnk(2, "Password Change", "/mock/security/password.jsp"))
				insDoc(aux2, gLnk(0, "Log out", "/mock/security/logout.jsp"))

	insDoc(foldersTree, gLnk(2, "About JRun Admin", "/mock/about.jsp"))
	
